<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>BRE Coins</title>
<meta name="description" content=""/>
<?php include('inc/head.php'); ?>
</head>

<body>
<?php include('inc/nav.php'); ?>
<div class="intros">
<div class="intro_bg_termos">
    
<!-- BLOCO TÍTULO COM IMAGEM -->
<section class="no-padding  quem-somos">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        	<h1 class="montserrat-light branco text-center titulo-com-imagem font-size-60">TERMOS E POLÍTICAS</h1>
      </div>
    </div>
  </div>
</section>
<!-- BLOCO TÍTULO COM IMAGEM END -->
    
    </div>
</div>


<section class="no-padding" id="termos">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
 		<p><h4>TERMOS E CONDI&Ccedil;&Otilde;ES DE USO - BRE COINS LTDA.</h4></p>
<p>Estes termos e condi&ccedil;&otilde;es de uso se aplicam aos servi&ccedil;os prestados pela pessoa jur&iacute;dica de direito privado, <strong>BRE COINS LTDA.</strong> (denominada "BRE COINS"), inscrita no CNPJ sob n&ordm; 29.103.574/0001-77, com sede e domic&iacute;lio na Av. Brigadeiro Faria Lima, 2277, conjunto 801, CEP 014.52-000, S&atilde;o Paulo/SP, detentora de um s&iacute;tio eletr&ocirc;nico (denominado "BRE COINS") que opera com o armazenamento e transa&ccedil;&otilde;es de compra, venda e transfer&ecirc;ncia de moedas digitais criptografadas, disponibilizada por meio do seguinte dom&iacute;nio <a href="http://www.brecoins.com.br">www.brecoins.com.br</a>.</p>
<p><strong>1.** GLOSS&Aacute;RIO DE TERMOS NESTE DOCUMENTO**</strong></p>
<p>O dom&iacute;nio virtual da BRE COINS operar&aacute; sob os seguintes termos:</p>
<p><strong>Assinatura Digital</strong> :c&oacute;digo criptografado que garante a validade de uma transa&ccedil;&atilde;o envolvendo moeda digital.</p>
<p><strong>Bitcoin</strong> :moeda digital que pode ser transacionada por meio da plataforma.</p>
<p><strong>Blockchain:</strong> tecnologia respons&aacute;vel por controlar e organizar a mobilidade de uma determinada moeda digital.</p>
<p><strong>Carteira</strong> : local onde s&atilde;o armazenadas as chaves privadas que d&atilde;o acesso &agrave;s moedas digitais de posse do usu&aacute;rio.</p>
<p><strong>Chave privada</strong> : conjunto de dados codificados que d&atilde;o acesso &agrave; moeda digital e possibilita sua movimenta&ccedil;&atilde;o.</p>
<p><strong>Confirma&ccedil;&atilde;o</strong> : quando uma transa&ccedil;&atilde;o &eacute; validada e inclu&iacute;da na <em>blockchain.</em></p>
<p><strong>Corretagem</strong> : intermedia&ccedil;&atilde;o de transa&ccedil;&otilde;es entre usu&aacute;rios por interm&eacute;dio da plataforma.</p>
<p><strong>Livro de Ofertas</strong> : registro p&uacute;blico das inten&ccedil;&otilde;es de compra e venda de moeda digital dentro da plataforma.</p>
<p><strong>Moedas Digitais</strong> : <em>tokens</em> (c&oacute;digos) digitais que funcionam como moeda.</p>
<p><strong>Ordem de compra ou venda</strong> : instru&ccedil;&atilde;o enviada pelo usu&aacute;rio por meio da plataforma que indica a inten&ccedil;&atilde;o de compra ou venda de moeda digital.</p>
<p><strong>Plataforma</strong> : sistema fornecido pela BRE COINS o qual os usu&aacute;rios podem realizar compras e vendas de moedas digitais.</p>
<p><strong>Transa&ccedil;&atilde;o</strong> : compra, venda ou movimenta&ccedil;&atilde;o de moeda digital realizada pelo usu&aacute;rio.</p>
<p><strong>Usu&aacute;rio</strong> : indiv&iacute;duo que utiliza a plataforma para realizar transa&ccedil;&otilde;es de compra e venda de moeda digital, podendo este representar pessoa f&iacute;sica ou jur&iacute;dica.</p>
<p><strong>Verifica&ccedil;&atilde;o</strong> : processo de valida&ccedil;&atilde;o das informa&ccedil;&otilde;es fornecidas pelo usu&aacute;rio no momento do cadastro.</p>
<h4><strong>2.</strong>** DO OBJETO**</h4>
<p><strong>2.1</strong> O presente termo define as condi&ccedil;&otilde;es pelas quais os usu&aacute;rios do site online poder&atilde;o acessar e usufruir das funcionalidades do sistema operacional da BRE COINS</p>
<p><strong>2.2</strong> Ades&atilde;o &eacute; fundamental para a opera&ccedil;&atilde;o das funcionalidades que o dom&iacute;nio virtual da BRE COINS oferece.</p>
<p>&nbsp;</p>
<p><strong>2.3</strong> Moeda virtual &eacute; definida como o <strong>dinheiro digital</strong> , aceito por pessoas f&iacute;sicas e jur&iacute;dicas como forma de pagamento e podendo ser transferido, armazenado e trocado eletronicamente.</p>
<p><strong>2.4</strong> A referida moeda constitui objeto de opera&ccedil;&atilde;o das transa&ccedil;&otilde;es a serem realizadas pelos usu&aacute;rios do site da BRE COINS.</p>
<h4><strong>3.</strong>** DA <strong>** ACEITA&Ccedil;&Atilde;O DOS TERMOS E CONDI&Ccedil;&Otilde;ES DE USO</strong></h4>
<p><strong>3.1</strong> Todo aquele que desejar ter acesso aos servi&ccedil;os ofertados pelo site (www.brecoins.com.br) dever&aacute; se informar acerca das diretrizes operacionais que comp&otilde;em o presente instrumento, as quais restar&atilde;o dispon&iacute;veis para pronta e ampla consulta em _# [ANNOTATION:</p>
<p>BY 'Gabriela Meschini' ON '2017-08-24T23:26:00'GM NOTE: 'Perguntar ao Victor se, de fato, haver&aacute; tal link (espec&iacute;fico para tal situa&ccedil;&atilde;o). ']__link_pr&oacute;prio no site.</p>
<p><strong>3.2</strong> Ao usufruir dos servi&ccedil;os prestados pela BRE COINS, o usu&aacute;rio <strong>aceita inteiramente</strong> as presentes normas e compromete-se a observ&aacute;-las, sob risco de penalidades aplic&aacute;veis.</p>
<p><strong>3.2.1.</strong>Prefacialmente &agrave; navega&ccedil;&atilde;o no dom&iacute;nio virtual, dever&aacute; o usu&aacute;rio cientificar-se a respeito de eventuais modifica&ccedil;&otilde;es ou atualiza&ccedil;&otilde;es deste instrumento, visto que este poder&aacute; sofrer altera&ccedil;&otilde;es peri&oacute;dicas, seja por quest&otilde;es legais ou estrat&eacute;gicas da BRE COINS.</p>
<p><strong>3.2.2</strong> A comunica&ccedil;&atilde;o de eventuais altera&ccedil;&otilde;es e atualiza&ccedil;&otilde;es ser&aacute; enviada aos usu&aacute;rios por interm&eacute;dio do pr&oacute;prio sistema, bem como via e-mail, devendo este estar constantemente atualizado.</p>
<p><strong>3.2.3</strong> O usu&aacute;rio deve se cientificar de todas essas modifica&ccedil;&otilde;es, altera&ccedil;&otilde;es sistem&aacute;ticas e operacionais, al&eacute;m de atualiza&ccedil;&otilde;es e corre&ccedil;&otilde;es t&eacute;cnicas antes de operar.</p>
<p><strong>3.3</strong> Caso o usu&aacute;rio n&atilde;o concorde com quaisquer das disposi&ccedil;&otilde;es aqui contidas, deve imediatamente abster-se de utilizar o servi&ccedil;o.</p>
<p><strong>3.4</strong> Para usufruto do site, os usu&aacute;rios dever&atilde;o realizar um cadastro pr&eacute;vio e responder pela veracidade e atualiza&ccedil;&atilde;o dos dados informados quando do cadastro.</p>
<h4><strong>4.</strong>** DA NAVEGA&Ccedil;&Atilde;O E GEST&Atilde;O DO SITE**</h4>
<p><strong>4.1</strong> O gestor do site www.brecoins.com.br se compromete a utilizar todas as solu&ccedil;&otilde;es t&eacute;cnicas &agrave; sua disposi&ccedil;&atilde;o para permitir o acesso ao <strong>servi&ccedil;o</strong> **# [ANNOTATION:</p>
<p>BY 'Gabriela Meschini' ON '2017-08-24T23:35:00'GM NOTE: 'Mant&eacute;m essa obriga&ccedil;&atilde;o ou pode o site inoperar algum dia?']<strong>**24 (vinte e quatro) horas por dia, 7 (sete) dias por semana</strong>. No entanto, ele poder&aacute;, <strong>a qualquer momento</strong> , interromper, limitar ou suspender o acesso ao site ou a algumas de suas p&aacute;ginas, no intuito de realizar atualiza&ccedil;&otilde;es, modifica&ccedil;&otilde;es de conte&uacute;do ou qualquer a&ccedil;&atilde;o necess&aacute;ria ao bom funcionamento do site.</p>
<p><strong>4.2</strong> Os presentes termos e condi&ccedil;&otilde;es de uso se aplicam a todas as extens&otilde;es do site, em aplicativos de <em>smartphones</em>, em redes sociais ou em comunidades, tanto as j&aacute; existentes, bem como &agrave;quelas ainda a serem implementadas.</p>
<h4><strong>5.</strong>** DO CADASTRO DO USU&Aacute;RIO E DOS DOCUMENTOS NECESS&Aacute;RIOS**</h4>
<p><strong>5.1</strong> Os servi&ccedil;os disponibilizados pela BRE COINS apenas poder&atilde;o ser acessados por pessoas plenamente capazes, conforme o Direito Brasileiro. Todos os que n&atilde;o possu&iacute;rem plena capacidade civil (menores de 18 anos n&atilde;o emancipados, pr&oacute;digos, &eacute;brios habituais ou viciados em t&oacute;xicos e pessoas que n&atilde;o puderem exprimir sua vontade, por motivo transit&oacute;rio ou permanente) dever&atilde;o ser devidamente assistidos por seus representantes legais, que se responsabilizar&atilde;o pelo cumprimento das presentes disposi&ccedil;&otilde;es.</p>
<p><strong>5.2</strong> No caso da cl&aacute;usula "4.1" acima, a BRE COINS encaminhar&aacute; aos respons&aacute;veis, competente "Termo de Responsabilidade" que dever&aacute; ser assinado, com reconhecimento de firma, pelo seu representante legal e enviado de volta ao site para aprova&ccedil;&atilde;o.</p>
<p><strong>5.3</strong> Ao usu&aacute;rio ser&aacute; permitido manter <strong>apenas uma conta</strong> junto ao site. Contas duplicadas ser&atilde;o automaticamente desativadas pelo gestor do site, sem preju&iacute;zo das demais penalidades aplic&aacute;veis.</p>
<p><strong>5.4</strong> Para o devido cadastramento, valida&ccedil;&atilde;o, dep&oacute;sito e retirada de valores em real, no que tange aos servi&ccedil;os oferecidos pela BRE COINS, o usu&aacute;rio dever&aacute; fornecer integralmente os dados requeridos, al&eacute;m dos documentos citados a seguir: (a) <strong>N&uacute;mero do CPF do usu&aacute;rio</strong> ; (b) <strong>Carteira Nacional de Habilita&ccedil;&atilde;o</strong> ; (c) <strong>Comprovante de Endere&ccedil;o</strong> <strong>com data m&aacute;xima de 3 (tr&ecirc;s) meses anteriores</strong>; e (d) <strong>Foto do usu&aacute;rio (tipo "selfie") ao lado de seu documento pessoal</strong>.</p>
<p><strong>5.5</strong> Todas as informa&ccedil;&otilde;es fornecidas pelo usu&aacute;rio devem ser precisas, verdadeiras e atualizadas, al&eacute;m de enviadas <strong>por meio de foto</strong> ( <strong>nunca escaneadas</strong> ). Excepcionalmente, e quando requerido pela BRE COINS, os documentos ser&atilde;o enviados mediante c&oacute;pia autenticada.</p>
<p><strong>5.6</strong> Em qualquer caso, o usu&aacute;rio responder&aacute;, em &acirc;mbito c&iacute;vel e criminal, pela veracidade, exatid&atilde;o e autenticidade dos dados informados.</p>
<p><strong>5.7</strong> O usu&aacute;rio deve fornecer um endere&ccedil;o de <em>e-mail</em> v&aacute;lido, por meio do qual o site realizar&aacute; todos os contatos necess&aacute;rios. Todas as comunica&ccedil;&otilde;es enviadas para o referido endere&ccedil;o eletr&ocirc;nico <strong>ser&atilde;o consideradas lidas pelo usu&aacute;rio</strong> , que se compromete, assim, a consultar regularmente suas mensagens recebidas e a respond&ecirc;-las em prazo razo&aacute;vel.</p>
<p><strong>5.8</strong> Ap&oacute;s a confirma&ccedil;&atilde;o de seu cadastro, o usu&aacute;rio possuir&aacute; um login de acesso e uma senha pessoais. <strong>Estes dados de conex&atilde;o n&atilde;o poder&atilde;o ser informados pelo usu&aacute;rio a terceiros, sendo de inteira responsabilidade desse o uso que do acesso seja feito</strong>. O usu&aacute;rio se compromete a comunicar imediatamente o gestor do site se suspeitar de quaisquer atividades inesperadas em sua conta.</p>
<p><strong>5.9</strong> Al&eacute;m do fornecimento de login e senha, a BRE COINS <strong>disponibilizar&aacute; ao usu&aacute;rio um</strong> <strong>plug-in</strong> <strong>de seguran&ccedil;a</strong> para que este possa operar no site.</p>
<p><strong>5.10</strong> Fica vedada a cess&atilde;o, venda, aluguel ou transfer&ecirc;ncia, de qualquer forma, da conta de acesso.</p>
<p><strong>5.11</strong> Ser&aacute; <strong>automaticamente exclu&iacute;do</strong> usu&aacute;rio que descumprir quaisquer das normas contidas no presente instrumento, sendo-lhe vedado realizar nova inscri&ccedil;&atilde;o no site.</p>
<p><strong>5.12</strong> O usu&aacute;rio poder&aacute;, a qualquer tempo e sem necessidade de justificativa, requerer o cancelamento de seu cadastro junto ao site, desde que n&atilde;o sejam verificadas pend&ecirc;ncias em aberto.</p>
<p><strong>5.13</strong> O cadastro de pessoas jur&iacute;dicas como usu&aacute;rias dever&aacute; ser realizado necessariamente por um representante legal devidamente autorizado para tanto, mediante comprova&ccedil;&atilde;o respectiva.</p>
<p><strong>5.14</strong> O cadastro &eacute; gratuito, por&eacute;m ser&atilde;o cobradas tarifas pelos servi&ccedil;os prestados, de acordo com o <em>Fee Board</em>, dispon&iacute;vel no site.</p>
<p><strong>5.15</strong> Para a utiliza&ccedil;&atilde;o dos servi&ccedil;os e opera&ccedil;&otilde;es do site, quando da compra, venda ou transfer&ecirc;ncia de moedas virtuais, &eacute; necess&aacute;rio que o cadastro do usu&aacute;rio esteja <strong>plenamente validado</strong>. Para tanto, a BRE COINS realizar&aacute; um procedimento de verifica&ccedil;&atilde;o dos dados informados e poder&aacute; solicitar ao usu&aacute;rio o envio de mais documentos al&eacute;m dos anteriormente solicitados, conforme cl&aacute;usula "4.4". A valida&ccedil;&atilde;o do cadastro do usu&aacute;rio &eacute; de mera liberalidade da BRE COINS, que poder&aacute;, <strong>sem qualquer justificativa</strong> , recusar a valida&ccedil;&atilde;o de qualquer conta.</p>
<h4><strong>6.</strong>** DAS RESPONSABILIDADES SUSCET&Iacute;VEIS**</h4>
<p><strong>6.1</strong> O gestor do site se responsabilizar&aacute; pelos defeitos ou v&iacute;cios encontrados nos servi&ccedil;os prestados pela BRE COINS, desde que lhes tenha dado causa. Defeito ou v&iacute;cios t&eacute;cnicos ou operacionais originados no pr&oacute;prio sistema do usu&aacute;rio <strong>n&atilde;o</strong> <strong>ser&atilde;o de responsabilidade do gestor</strong>.</p>
<p><strong>6.2</strong> O gestor apenas se responsabiliza pelas informa&ccedil;&otilde;es que foram por ele divulgadas. <strong>As demais informa&ccedil;&otilde;es inclu&iacute;das pelo usu&aacute;rio ser&atilde;o de responsabilidade deste</strong>.</p>
<p><strong>6.3</strong> S&atilde;o de responsabilidade do usu&aacute;rio: (a) <em>correta utiliza&ccedil;&atilde;o do site e de seus servi&ccedil;os, prezando pela boa conviv&ecirc;ncia, pelo respeito e cordialidade m&uacute;tuos</em>; (b) <em>cumprimento das disposi&ccedil;&otilde;es contidas neste termo, bem como &agrave;s normas do Direito nacional e internacional</em>; (c) <strong>prote&ccedil;&atilde;o dos dados de acesso disponibilizados para acesso &agrave; sua conta (login e senha</strong>).</p>
<p><strong>6.4</strong> O gestor <strong>n&atilde;o</strong> se responsabilizar&aacute;: (a) pelas caracter&iacute;sticas intr&iacute;nsecas da internet, principalmente referentes &agrave; confiabilidade e &agrave; proced&ecirc;ncia das informa&ccedil;&otilde;es circulantes nesta rede; (b) pelos conte&uacute;dos ou atividades il&iacute;citas eventualmente praticadas por meio do site de propriedade da BRE COINS.</p>
<h4><strong>7.</strong>** DOS LINKS EXTERNOS**</h4>
<p><strong>7.1</strong> O site www.brecoins.com.br poder&aacute; conter <em>links</em> externos, que remeter&atilde;o o usu&aacute;rio para outras p&aacute;ginas virtuais sobre as quais o gestor n&atilde;o exerce controle e, por este motivo, se isenta de quaisquer e eventuais responsabilidades.</p>
<p><strong>7.2</strong> Poder&atilde;o ser inclu&iacute;dos <em>links</em> nas p&aacute;ginas e documentos do site, a crit&eacute;rio do gestor.</p>
<p><strong>7.3</strong> N&atilde;o ser&aacute; autorizada a inclus&atilde;o de p&aacute;ginas que divulguem quaisquer tipos de informa&ccedil;&otilde;es il&iacute;citas, violentas, pol&ecirc;micas, pornogr&aacute;ficas, xenof&oacute;bicas, discriminat&oacute;rias ou ofensivas.</p>
<h4><strong>8.</strong>** DA FUNCIONALIDADE, DISPOSI&Ccedil;&Otilde;ES DE UTILIZA&Ccedil;&Atilde;O DAS OPERA&Ccedil;&Otilde;ES, RESTRI&Ccedil;&Otilde;ES E LIMITES**</h4>
<p><strong>8.1</strong> A BRE COINS oferece os servi&ccedil;os de intermedia&ccedil;&atilde;o e agenciamento da compra, venda e transfer&ecirc;ncia de moedas virtuais criptografadas, possibilitando que os usu&aacute;rios possam negociar entre si, sem que a BRE COINS participe do contato, negocia&ccedil;&atilde;o ou efetiva&ccedil;&atilde;o do neg&oacute;cio.</p>
<p><strong>8.2</strong> Ap&oacute;s valida&ccedil;&atilde;o do cadastro do usu&aacute;rio, o site cria uma conta financeira virtual, a qual poder&aacute; ser administrada pelo acesso do mesmo com seu <em>login</em>, senha e <em>plug-in</em>.</p>
<p><strong>8.3</strong> A referida contarepresenta uma ilustra&ccedil;&atilde;o da aplica&ccedil;&atilde;o financeira administrada e investida na conta do site. O dinheiro nela inserido poder&aacute; ser retirado pelo usu&aacute;rio para transfer&ecirc;ncia banc&aacute;ria de sua titularidade ou ser colocado &agrave; venda, por interm&eacute;dio das opera&ccedil;&otilde;es de venda oferecidas pelo site.</p>
<p><strong>8.4</strong>** As transa&ccedil;&otilde;es, negocia&ccedil;&otilde;es e opera&ccedil;&otilde;es internas entre os usu&aacute;rios s&atilde;o de inteira responsabilidade destes. A BRE COINS possibilita o armazenamento das moedas virtuais e intermedia as opera&ccedil;&otilde;es de compra, venda e transfer&ecirc;ncia de <strong>** moedas digitais.</strong></p>
<p><strong>8.5</strong> Para a utiliza&ccedil;&atilde;o dos servi&ccedil;os ofertados pela BRE COINS, o usu&aacute;rio se mant&eacute;m ciente de que as opera&ccedil;&otilde;es realizadas est&atilde;o sob sua responsabilidade e risco, uma vez que a BRE COINS atua meramente como mantenedora do site, n&atilde;o sendo esta respons&aacute;vel por eventuais perdas e danos, preju&iacute;zos e/ou lucros cessantes sofridos, em decorr&ecirc;ncia das negocia&ccedil;&otilde;es.</p>
<p><strong>8.6</strong>** A BRE COINS N&Atilde;O ATUA COMO CONSULTORA DE INVESTIMENTOS e/ou aplica&ccedil;&atilde;o de moedas virtuais, sendo que os seus usu&aacute;rios devem estar previamente informados quanto &agrave; valoriza&ccedil;&atilde;o, oscila&ccedil;&atilde;o e formas de investimentos de moedas virtuais.**</p>
<p><strong>8.7</strong> A venda de moedas virtuais s&oacute; ser&aacute; autorizada pelo site caso o vendedor, devidamente habilitado, j&aacute; disponha de moedas virtuais em sua conta, na quantia correspondente ao valor da venda.</p>
<p><strong>8.7.1</strong> As moedas virtuais podem ser armazenadas mediante aporte no endere&ccedil;o fornecido pelo site e estar&atilde;o dispon&iacute;veis para venda em <strong>at&eacute; 24 (vinte e quatro) horas</strong>, respeitado o expediente banc&aacute;rio.</p>
<p><strong>8.7.2</strong> &Eacute; <strong>vedado</strong> o dep&oacute;sito (aporte) em cheque, sendo somente permitida a opera&ccedil;&atilde;o via transfer&ecirc;ncia banc&aacute;ria (TED).</p>
<p><strong>8.8</strong> O valor de venda &eacute; estabelecido pelo usu&aacute;rio vendedor.</p>
<p><strong>8.9</strong> O usu&aacute;rio fica, desde j&aacute;, ciente de que a efetiva&ccedil;&atilde;o do an&uacute;ncio da venda representa uma proposta v&aacute;lida para todos os fins, sendo que ap&oacute;s o aceite por outro usu&aacute;rio, a transa&ccedil;&atilde;o de compra e venda se concretizar&aacute; automaticamente, <strong>n&atilde;o podendo ser desfeita ou alterada</strong> , <em>devendo o usu&aacute;rio vendedor arcar pelos preju&iacute;zos que eventualmente causar ao demais usu&aacute;rios aceitantes da proposta, n&atilde;o sendo a BRE COINS responsabilizada por tal situa&ccedil;&atilde;o.</em></p>
<p><strong>8.10</strong> Para comprar moedas virtuais o usu&aacute;rio dever&aacute; requerer no site um an&uacute;ncio quanto ao interesse de compra, devendo ter armazenado em sua conta, valor suficiente para a opera&ccedil;&atilde;o a que deseja realizar.</p>
<p><strong>8.11</strong> O valor de compra &eacute; estabelecido pelo pr&oacute;prio usu&aacute;rio, sem qualquer manifesta&ccedil;&atilde;o de interfer&ecirc;ncia da BRE COINS.</p>
<p><strong>8.12</strong> O usu&aacute;rio fica, desde j&aacute;, ciente de que o an&uacute;ncio sobre o interesse em comprar moedas virtuais representa uma proposta v&aacute;lida para todos os fins, sendo que, ap&oacute;s o aceite por outro usu&aacute;rio, a transa&ccedil;&atilde;o de compra e venda se concretizar&aacute; automaticamente, <strong>n&atilde;o podendo ser desfeita ou alterada</strong> , <em>devendo o usu&aacute;rio vendedor arcar pelos preju&iacute;zos que eventualmente causar ao demais usu&aacute;rios aceitantes da proposta, n&atilde;o sendo a BRE COINS responsabilizada por tal situa&ccedil;&atilde;o.</em></p>
<p><strong>8.13</strong> A compra poder&aacute; ser aceita de forma parcial por outro usu&aacute;rio, podendo ou n&atilde;o o valor remanescente desta continuar v&aacute;lido para que outro usu&aacute;rio o aceite, a crit&eacute;rio dos negociantes da opera&ccedil;&atilde;o.</p>
<p><strong>8.14</strong> Quanto ao armazenamento de moedas virtuais, o usu&aacute;rio resta ciente de que poder&aacute; armazenar as moedas virtuais em sua conta, seja para vend&ecirc;-las, transferi-las ou somente armazen&aacute;-las.</p>
<p><strong>8.15</strong> A transfer&ecirc;ncia de moedas virtuais poder&aacute; se dar para outro site ou plataforma # [ANNOTATION:</p>
<p>BY 'Gabriela Meschini' ON '2017-08-24T20:45:00'GM NOTE: 'Ser&aacute; cobrado 2% tamb&eacute;m aqui?'] virtual.</p>
<p><strong>8.16</strong> Independentemente das cl&aacute;usulas acima, o usu&aacute;rio, a qualquer tempo, poder&aacute; solicitar a # [ANNOTATION:</p>
<p>BY 'Gabriela Meschini' ON '2017-08-24T23:42:00'GM NOTE: 'Integral ou limitado a 100 mil reais? '] transfer&ecirc;ncia dos valores investidos, em dinheiro, para a conta banc&aacute;ria informada quando do cadastro, respeitado o prazo estabelecido na cl&aacute;usula 8.4.2.2.</p>
<p><strong>8.16.1 </strong>A conta banc&aacute;ria informada, al&eacute;m de v&aacute;lida e de titularidade do usu&aacute;rio, dever&aacute; estar situada no mesmo pa&iacute;s de origem dos fundos a serem transferidos.</p>
<p><strong>8.17</strong> A BRE COINS poder&aacute; transferir os valores em dinheiro, armazenados para a conta banc&aacute;ria do usu&aacute;rio, <strong>a qualquer tempo</strong>.</p>
<p><strong>8.17.1</strong> Neste caso, quando a quantia acima referida retornar para a conta do usu&aacute;rio, a BRE COINS poder&aacute;, a seu crit&eacute;rio, descontar valores correspondestes &agrave; taxas aplic&aacute;veis.</p>
<h4><strong>9.</strong>** DAS TAXAS E/OU TARIFAS DAS OPERA&Ccedil;&Otilde;ES**</h4>
<p><strong>9.1</strong> Pelos servi&ccedil;os ora ofertados pela BRE COINS, ser&atilde;o os valores estabelecidos no <em>Fee Board</em>.</p>
<p><strong>9.2</strong> A BRE COINS se reserva no direito de alterar o <em>Fee Board</em> <strong>sem qualquer comunica&ccedil;&atilde;o pr&eacute;via ao usu&aacute;rio.</strong></p>
<p><strong>9.3</strong> Os valores relativos &agrave;s tarifas ser&atilde;o debitados diretamente dos valores armazenados na conta do usu&aacute;rio.</p>
<p><strong>9.4</strong> As tarifas a serem debitadas da conta do usu&aacute;rio incidir&atilde;o nas seguintes opera&ccedil;&otilde;es abaixo delimitadas.</p>
<p><strong>9.4.1</strong> <strong>Aporte/Dep&oacute;sito de valores em real para a compra de moedas virtuais &ndash; 2% do valor do aporte</strong> : Trata-se de um <em>fee</em> de ades&atilde;o e se d&aacute; quando o usu&aacute;rio efetua um dep&oacute;sito em moeda corrente nacional (real), destinado &agrave; compra de moedas virtuais por meio do site, sendo, por isso, cobrada uma taxa de 2% sobre o valor depositado. Desta forma, o saldo restante dispon&iacute;vel ao usu&aacute;rio ser&aacute; o valor depositado, devidamente descontado o valor da taxa desta opera&ccedil;&atilde;o (aporte/dep&oacute;sito).</p>
<p><strong>9.4.2</strong> <strong>Retirada de valores em real (no caso de j&aacute; existirem transa&ccedil;&otilde;es anteriores) &ndash; 2%</strong>: Se d&aacute; quando o usu&aacute;rio decide promover a retirada dos valores armazenados em real, desde que este j&aacute; tenha operado no site. Assim sendo, ser&aacute; descontado do valor retirado/transferido, a taxa de 2% (retirada).</p>
<p><strong>9.4.2.1</strong> Caso o usu&aacute;rio deseje fazer a retirada de valores e, ao mesmo tempo, n&atilde;o tenha realizado nenhuma opera&ccedil;&atilde;o no site, n&atilde;o ser&aacute; cobrada qualquer taxa.</p>
<p><strong>9.4.2.2</strong> O prazo para devolu&ccedil;&atilde;o do valor solicitado pelo usu&aacute;rio come&ccedil;a a contar do dia em que este requereu o regaste, estando este dispon&iacute;vel dentro de 02 (dois) dias &uacute;teis, ap&oacute;s a solicita&ccedil;&atilde;o.</p>
<p><strong>9.4.3</strong> <strong>Venda de moedas virtuais &ndash; 2%</strong>** :** O an&uacute;ncio de venda de moedas criptografas &eacute; gratuito. A cobran&ccedil;a da taxa de venda de 2% se d&aacute; quando a venda for aceita, total ou parcialmente, por outro usu&aacute;rio, a ser cobrada de quem publicou o an&uacute;ncio de venda. Deste modo, o saldo em real dispon&iacute;vel ser&aacute; o valor de venda descontado o valor da tarifa (2%) desta opera&ccedil;&atilde;o (venda).</p>
<p><strong>9.4.4</strong> <strong>Compra de moedas virtuais &ndash; 2%</strong>** :** O an&uacute;ncio quanto ao interesse de compra de moedas criptografas &eacute; gratuito. A cobran&ccedil;a da taxa de compra de 2% se d&aacute; quando esta for aceita, total ou parcialmente, por outro usu&aacute;rio, a ser cobrada de quem publicou o interesse de compra. Deste modo, o saldo em <em>moedas virtuais</em> dispon&iacute;vel ser&aacute; o valor de compra depositado pelo comprador, descontado o valor da tarifa (2%) desta opera&ccedil;&atilde;o (venda).</p>
<p><strong>9.5</strong>** O limite di&aacute;rio de retirada/resgate &eacute; de R$ 100.000,00 (cem** **# [ANNOTATION:</p>
<p>BY 'Gabriela Meschini' ON '2017-08-24T21:12:00'GM NOTE: 'Confirmar!'] <strong>**mil</strong> **reais). **</p>
<p><strong>9.6</strong> Caso o usu&aacute;rio deseje obter a lisura da moeda virtual, por interm&eacute;dio do selo de certifica&ccedil;&atilde;o da BRE COINS, este dever&aacute; pagar o equivalente &agrave; 2% pela opera&ccedil;&atilde;o.</p>
<p><strong>9.7</strong> # [ANNOTATION:</p>
<p>BY 'Gabriela Meschini' ON '2017-08-24T21:00:00'GM NOTE: 'As transa&ccedil;&otilde;es ser&atilde;o feitas em real ou d&oacute;lar? '] A venda das moedas digitais observar&aacute; <strong>necessariamente</strong> a cota&ccedil;&atilde;o em real do momento em que o usu&aacute;rio enviar a ordem de venda e esta for aprovada e disponibilizada na conta do comprador. Em seguida, a BRE COINS <strong>dever&aacute; notificar o vendedor a respeito</strong>. Ultrapassada tal etapa, as moedas digitais estar&atilde;o dispon&iacute;veis dentro de 02 (dois) dias &uacute;teis.</p>
<p><strong>9.8</strong> As transa&ccedil;&otilde;es e opera&ccedil;&otilde;es internas do site sempre respeitar&atilde;o os expedientes banc&aacute;rios, <em>salvo se o comprador j&aacute; tiver aportado em sua conta o valor da moeda digital, caso em que a transa&ccedil;&atilde;o ser&aacute; autorizada pela BRE COINS, independentemente de hor&aacute;rio banc&aacute;rio, e tendo por base o &uacute;ltimo c&acirc;mbio dispon&iacute;vel dentro do expediente banc&aacute;rio</em>. No entanto, <strong>a transa&ccedil;&atilde;o somente ser&aacute; formalmente efetivada no primeiro expediente banc&aacute;rio.</strong></p>
<p><strong>9.9</strong> Aceitando o presente instrumento, o usu&aacute;rio concorda em pagar &agrave; BRE COINS os valores relativos &agrave;s taxas incidentes pelos servi&ccedil;os prestados, conforme <em>Fee Board</em> disponibilizado no site. Ademais, a BRE COINS se reserva no direito de alterar, a qualquer tempo, seja em car&aacute;ter permanente ou transit&oacute;rio, sendo que quaisquer modifica&ccedil;&otilde;es ser&atilde;o comunicadas por meio do s&iacute;tio eletr&ocirc;nico www.brecoins.com.br.</p>
<h4><strong>10. RESCIS&Atilde;O</strong> , INTERRUP&Ccedil;&Atilde;O, SUSPENS&Atilde;O E CANCELAMENTO CONTRATUAL</h4>
<p><strong>10.1</strong> O usu&aacute;rio poder&aacute; rescindir o referido contrato, <strong>a qualquer tempo</strong> , <strong>n&atilde;o sendo devido o pagamento de multa</strong>. Tal ato se dar&aacute; por interm&eacute;dio de um "Requerimento de Cancelamento" do cadastro sob titularidade do usu&aacute;rio, sendo o resgate de valores ocorrido na forma da cl&aacute;usula 8.4.2. e 8.4.2.2, bem como observado a limita&ccedil;&atilde;o da cl&aacute;usula 8.5.</p>
<p><strong>10.2</strong> O mencionado cancelamento <strong>s&oacute; ser&aacute; efetivado se n&atilde;o existirem registros de fundos (valores em real ou em moedas virtuais armazenados na conta do usu&aacute;rio)</strong>, incumbindo ao usu&aacute;rio a realiza&ccedil;&atilde;o dos respectivos resgates, vendas ou transfer&ecirc;ncias, se cab&iacute;vel.</p>
<p><strong>10.3</strong> Depois de suspenso ou cancelado o cadastro do usu&aacute;rio, realizado por este ou pela BRE COINS, aquele fica ciente que <strong>n&atilde;o ter&aacute; mais acesso</strong> ou direito ao resgate de informa&ccedil;&otilde;es acerca de transa&ccedil;&otilde;es realizadas, <strong>n&atilde;o</strong> cabendo &agrave; BRE COINS o dever de armazenamento dessas.</p>
<p><strong>10.4</strong> Caso haja qualquer suspeita por parte da BRE COINS acerca de eventual fraude ou qualquer atividade il&iacute;cita praticada sob seu s&iacute;tio eletr&ocirc;nico, poder&aacute; esta recorrer &agrave;s medidas legais aplic&aacute;veis, sem preju&iacute;zo da rescis&atilde;o imediata do presente, al&eacute;m da reten&ccedil;&atilde;o de eventuais fundos armazenados na conta do usu&aacute;rio, at&eacute; se conclu&iacute;rem as investiga&ccedil;&otilde;es.</p>
<p><strong>10.5</strong> Constituem motivos para suspens&atilde;o, cancelamento e/ou rescis&atilde;o do presente, de forma imediata e indefinida, a qualquer tempo e sem aviso pr&eacute;vio: <strong>(a) fornecimento de informa&ccedil;&otilde;es falsas, imprecisas, parciais ou duvidosas; (b) n&atilde;o fornecimento de documentos adicionais; (c) m&aacute;-f&eacute;; (d) viola&ccedil;&otilde;es das disposi&ccedil;&otilde;es do presente termo; (e) uso desleal e contr&aacute;rio ao presente; (f) pr&aacute;tica de condutas fraudulentas e/ou ilegais; (g) tentativa de</strong> <strong>double-spending</strong> <strong>(uso da mesma moeda virtual em opera&ccedil;&otilde;es distintas).</strong></p>
<p><strong>10.6</strong> As taxas j&aacute; descontadas n&atilde;o ser&atilde;o reembolsadas no caso de rescis&atilde;o contratual.</p>
<p><strong>10.7</strong> Verificada a inatividade da conta do usu&aacute;rio por mais de 4 (quatro) meses, o presente instrumento <strong>poder&aacute; ser unilateralmente rescindo</strong> pela BRE COINS.</p>
<p><strong>10.8</strong> As obriga&ccedil;&otilde;es admitidas com o aceite do presente instrumento permanecer&atilde;o mesmo ap&oacute;s a sua eventual rescis&atilde;o e continuar&atilde;o em vigor at&eacute; serem integralmente sanadas, inclusive no tocante &agrave;s opera&ccedil;&otilde;es internas efetuadas no site pelos usu&aacute;rios ou entre eles.</p>
<p><strong>10.9</strong> As moedas virtuais <strong>somente ser&atilde;o transferidas para a conta banc&aacute;ria ap&oacute;s a convers&atilde;o em real</strong>. No caso de suspens&atilde;o, cancelamento ou rescis&atilde;o contratual, por qualquer das partes, o usu&aacute;rio ter&aacute; o prazo de <strong>60 (sessenta) dias</strong> para indicar outro site com a mesma opera&ccedil;&atilde;o da BRE COINS para transfer&ecirc;ncia. Deixando de informar, a BRE COINS poder&aacute; fazer a convers&atilde;o em real, baseando-se na cota&ccedil;&atilde;o do dia informada em seu site e proceder &agrave; transfer&ecirc;ncia de valores para a conta banc&aacute;ria vinculada ao cadastro do usu&aacute;rio.</p>
<h4><strong>11.</strong>** DO SUPORTE T&Eacute;CNICO**</h4>
<p><strong>11.1</strong> O objeto do suporte t&eacute;cnico limitar-se-&aacute; aos esclarecimentos acerca do funcionamento e uso do site (via <em>e-mail</em>, telefone ou <em>chat online,</em> disponibilizados no site da BRE COINS), <strong>pressupondo o conhecimento m&iacute;nimo de manuseio pelo usu&aacute;rio</strong>. Pressup&otilde;e-se ainda, a <em>configura&ccedil;&atilde;o adequada do computador e/ou dispositivo m&oacute;vel no que se refere &agrave; utiliza&ccedil;&atilde;o do site e o bom estado de funcionamento do referido computador/dispositivo m&oacute;vel.</em></p>
<p><strong>11.2</strong> O suporte t&eacute;cnico estar&aacute; dispon&iacute;vel nos dias &uacute;teis, no hor&aacute;rio de <strong>8h &agrave;s 18h</strong> , de acordo com o calend&aacute;rio e hor&aacute;rio oficiais da capital do Brasil, a cidade de Bras&iacute;lia.</p>
<p><strong>11.3</strong> O Suporte T&eacute;cnico fornecido pela BRE COINS <strong>n&atilde;o abrange a conex&atilde;o com a internet, rede interna e computadores/dispositivos m&oacute;veis do usu&aacute;rio.</strong></p>
<h4><strong>12.</strong>** DOS DIREITOS AUTORAIS**</h4>
<p><strong>12.1</strong> A estrutura do site www.brecoins.com.br, bem como os textos, os gr&aacute;ficos, as imagens, as fotografias, os sons, os v&iacute;deos e as demais aplica&ccedil;&otilde;es inform&aacute;ticas que o comp&otilde;em s&atilde;o de propriedade do gestor e s&atilde;o protegidas pela legisla&ccedil;&atilde;o brasileira e internacional referente &agrave; propriedade intelectual.</p>
<p><strong>12.2</strong> Qualquer representa&ccedil;&atilde;o, reprodu&ccedil;&atilde;o, adapta&ccedil;&atilde;o ou explora&ccedil;&atilde;o parcial ou total dos conte&uacute;dos, marcas e servi&ccedil;os proposto pela BRE COINS, por qualquer meio que seja, sem autoriza&ccedil;&atilde;o pr&eacute;via, expressa e escrita do gestor, &eacute; estritamente vedada, podendo-se recorrer &agrave;s medidas c&iacute;veis e penais cab&iacute;veis.</p>
<p><strong>12.3</strong> O acesso n&atilde;o gera ao usu&aacute;rio qualquer direito de propriedade intelectual relativo ao site, o qual resta sob propriedade exclusiva do gestor.</p>
<p><strong>12.4</strong> &Eacute; vedado ao usu&aacute;rio incluir no site dados que possam modificar o seu conte&uacute;do ou apar&ecirc;ncia.</p>
<h4><strong>13.</strong>** DA POL&Iacute;TICA DE PRIVACIDADE E DO COMPLIANCE**</h4>
<p><strong>13.1</strong> Todos os dados pessoais fornecidos pelo usu&aacute;rio no momento de seu cadastro ou posteriormente, permanecer&atilde;o sob sigilo e n&atilde;o ser&atilde;o repassados a terceiros, exceto quando as informa&ccedil;&otilde;es fornecidas forem indispens&aacute;veis &agrave;s opera&ccedil;&otilde;es internas do site, no tocante &agrave; compra, venda ou transfer&ecirc;ncia de moedas virtuais entre outros usu&aacute;rios.</p>
<p><strong>13.2</strong> Nas demais situa&ccedil;&otilde;es, o gestor somente poder&aacute; transmitir os dados pessoais a terceiros quando o usu&aacute;rio o permitir expressamente ou quando presentes as hip&oacute;teses legais previstas na legisla&ccedil;&atilde;o aplic&aacute;vel &agrave; esp&eacute;cie, tais como requisi&ccedil;&atilde;o judicial.</p>
<p><strong>13.3</strong> Fica plenamente assegurada e garantida a confidencialidade dos dados pessoais fornecidos pelos usu&aacute;rios, devendo o gestor proteger o site contra tentativas de viola&ccedil;&otilde;es ou acessos clandestinos &agrave; sua base de dados.</p>
<p><strong>13.4</strong> O site recorre eventualmente &agrave;s t&eacute;cnicas de "cookies", que lhe permite analisar as estat&iacute;sticas e as informa&ccedil;&otilde;es sobre a navega&ccedil;&atilde;o do usu&aacute;rio. Estes dados de navega&ccedil;&atilde;o poder&atilde;o ser compartilhados com eventuais parceiros do site, buscando o melhor funcionamento do mesmo.</p>
<p><strong>13.5</strong> O usu&aacute;rio poder&aacute; se opor ao registro de "cookies" pelo site, desativando respectiva op&ccedil;&atilde;o no seu pr&oacute;prio navegador ou # [ANNOTATION:</p>
<p>BY 'Gabriela Meschini' ON '2017-08-24T23:47:00'GM NOTE: 'Caso o usu&aacute;rio o fa&ccedil;a (desative), tal ir&aacute; interferir na funcionalidade do site?'] aparelho.</p>
<p><strong>13.6</strong> Quanto &agrave; manuten&ccedil;&atilde;o dos registros de dados, a BRE COINS est&aacute; ciente de que dever&aacute; ter resguardados, em seu sistema operacional interno, todos os registros das transa&ccedil;&otilde;es (envolvendo pagamento, recibo, troca, convers&atilde;o, compra, venda ou transmiss&atilde;o de moedas virtuais); al&eacute;m de dados dos usu&aacute;rios; quantias ou valores das transa&ccedil;&otilde;es; m&eacute;todos de pagamento; entre outras opera&ccedil;&otilde;es realizadas no site, inclusive quanto &agrave;s transa&ccedil;&otilde;es incompletas, estando tais registros &agrave; disposi&ccedil;&atilde;o das entidades governamentais.</p>
<p><strong>13.7</strong> As moedas digitais e a origem dos recursos para sua aquisi&ccedil;&atilde;o s&atilde;o de inteira responsabilidade dos vendedores, sendo eventuais informa&ccedil;&otilde;es fraudulentas de responsabilidade integral de quem as fornece.</p>
<p><strong>13.8</strong> A BRE COINS est&aacute; ciente de que dever&aacute; tomar medidas razo&aacute;veis para detectar e prevenir a fraude, inclusive estabelecer e manter uma pol&iacute;tica escrita antifraude. Tal pol&iacute;tica deve, no m&iacute;nimo, incluir: <strong>(a) a identifica&ccedil;&atilde;o e avalia&ccedil;&atilde;o de &aacute;reas de risco relacionadas &agrave; fraude; (b) os procedimentos e controles para prote&ccedil;&atilde;o contra riscos identificados; (c) a atribui&ccedil;&atilde;o de responsabilidades para o monitoramento de riscos; e (d) procedimentos para avalia&ccedil;&atilde;o peri&oacute;dica e revis&atilde;o dos procedimentos, controles e mecanismos de monitoramento antifraude.</strong></p>
<p><strong>13.9</strong> A pol&iacute;tica interna da BRE COINS regida pelas normas de <em>compliance</em>, obrigando-se esta a cumprir todas as leis, regras e regulamento federais e estaduais aplic&aacute;veis.</p>
<p><strong>13.10</strong> A BRE COINS est&aacute; ciente de que deve manter e fazer cumprir as pol&iacute;ticas de <em>compliance</em> por escrito, incluindo pol&iacute;ticas em rela&ccedil;&atilde;o a <strong>antifraude, combate &agrave; lavagem de dinheiro (melhor delimitada na cl&aacute;usula 13), seguran&ccedil;a cibern&eacute;tica, seguran&ccedil;a de privacidade e informa&ccedil;&otilde;es</strong>, e qualquer outra pol&iacute;tica exigida por este termo, que deve ser revisada e aprovada pelo conselho dos diretores da BRE COINS ou um &oacute;rg&atilde;o governamental equivalente.</p>
<h4><strong>14.</strong>** DO COMBATE &Agrave; LAVAGEM DE DINHEIRO**</h4>
<p><strong>14.1</strong> O usu&aacute;rio se compromete em n&atilde;o usar dos servi&ccedil;os ora ofertados para fins il&iacute;citos, imorais e contr&aacute;rios aos bons costumes, nem mesmo praticar lavagem de dinheiro; financiar atividades e/ou organiza&ccedil;&otilde;es que envolvam terrorismo, m&aacute;fia, tr&aacute;fico de drogas, pessoas e/ou &oacute;rg&atilde;os humanos.</p>
<p><strong>14.2</strong> Em contrapartida, a BRE COINS se compromete a realizar uma avalia&ccedil;&atilde;o de risco inicial que considere os riscos legais, de <em>compliance</em>, financeiros e reputa&ccedil;&atilde;o associados &agrave;s atividades, servi&ccedil;os, usu&aacute;rios, e deve estabelecer, manter e fazer valer um programa de combate &agrave; lavagem de dinheiro com base nisso. A BRE COINS deve realizar avalia&ccedil;&otilde;es adicionais anualmente, ou com mais frequ&ecirc;ncia &agrave; medida que os riscos mudam, e deve modificar o seu programa de combate &agrave; lavagem de dinheiro, conforme apropriado, para refletir essas mudan&ccedil;as.</p>
<p><strong>14.3</strong> O programa de combate &agrave; lavagem de dinheiro da BRE COINS tem como premissas b&aacute;sicas as seguintes:</p>
<p>a) <strong>providenciar um sistema de controles internos, pol&iacute;ticas e procedimentos destinados a assegurar o cumprimento cont&iacute;nuo de todas as leis, regras e regulamentos aplic&aacute;veis ao combate &agrave; lavagem de dinheiro;</strong></p>
<p>b) <strong>providenciar testes independentes para o cumprimento e efic&aacute;cia do programa de combate &agrave; lavagem de dinheiro a ser conduzido por pessoal interno qualificado da BRE COINS, que n&atilde;o s&atilde;o respons&aacute;veis pelo projeto, instala&ccedil;&atilde;o, manuten&ccedil;&atilde;o ou opera&ccedil;&atilde;o de combate &agrave; lavagem de dinheiro, ou as pol&iacute;ticas e procedimentos que guiam sua opera&ccedil;&atilde;o, ou uma parte externa qualificada, pelo menos uma vez por ano;</strong></p>
<p>c) <strong>designar um indiv&iacute;duo qualificado ou indiv&iacute;duos em conformidade respons&aacute;vel pela coordena&ccedil;&atilde;o e monitoramento do cumprimento di&aacute;rio do programa de combate &agrave; lavagem de dinheiro; e</strong></p>
<p>d) <strong>fornecer treinamento cont&iacute;nuo para o pessoal apropriado para garantir que eles tenham uma compreens&atilde;o abrangente dos requisitos de combate &agrave; lavagem de dinheiro e permitir que eles identifiquem as transa&ccedil;&otilde;es necess&aacute;rias para serem reportados e manter registros necess&aacute;rios para serem mantidos de acordo com este termo.</strong></p>
<p><strong>14.4</strong> O programa de combate &agrave; lavagem de dinheiro inclui uma pol&iacute;tica escrita contra o combate &agrave; lavagem de dinheiro, revista e aprovada pelo conselho de diretores da BRE COINS.</p>
<h4><strong>15.</strong>** DA CONCESS&Atilde;O DE LICEN&Ccedil;A E USO**</h4>
<p><strong>15.1</strong> A BRE COINS, como propriet&aacute;ria do <em>software</em> objeto deste instrumento, neste ato e na melhor forma de direito, outorga ao usu&aacute;rio uma licen&ccedil;a de uso, em car&aacute;ter n&atilde;o exclusivo e n&atilde;o transfer&iacute;vel, para utiliza&ccedil;&atilde;o via internet e pelo site www.brecoins.com.br.</p>
<p><strong>15.2</strong> O usu&aacute;rio declara-se integral e totalmente respons&aacute;vel pelas informa&ccedil;&otilde;es inseridas no site e o modo de administra&ccedil;&atilde;o da sua conta. A BRE COINS, em hip&oacute;tese alguma ser&aacute; respons&aacute;vel pelas informa&ccedil;&otilde;es, senhas, entre outros conte&uacute;dos fornecidos pelo usu&aacute;rio.</p>
<p><strong>15.3</strong> A BRE COINS reserva-se no direito de atualizar, comercializar ou mesmo descontinuar o site, sempre que desejar.</p>
<p><strong>15.4</strong> No caso de descontinuidade, a BRE COINS garantir&aacute; o funcionamento por at&eacute; 3 (tr&ecirc;s) meses ap&oacute;s a data do an&uacute;ncio de descontinuidade.</p>
<h4><strong>16.</strong>** DA VIG&Ecirc;NCIA**</h4>
<p><strong>16.1</strong> O prazo de vig&ecirc;ncia do presente termo &eacute; <strong>indeterminado</strong>.</p>
<h4><strong>17.</strong>** DAS DISPOSI&Ccedil;&Otilde;S FINAIS**</h4>
<p><strong>17.1</strong> A incapacidade ou a mera liberalidade em n&atilde;o fazer cumprir quaisquer disposi&ccedil;&otilde;es deste instrumento n&atilde;o constitui ren&uacute;ncia de direitos, podendo ser exigido o seu cumprimento em qualquer momento.</p>
<p><strong>17.2</strong> Caso qualquer disposi&ccedil;&atilde;o deste termo for considerada inexequ&iacute;vel ou inv&aacute;lida, essa disposi&ccedil;&atilde;o ser&aacute; isoladamente invalidada e n&atilde;o atingir&aacute; o restante das disposi&ccedil;&otilde;es destes termos.</p>
<p><strong>17.3</strong> Os Termos e Condi&ccedil;&otilde;es de Uso da BRE COINS e a rela&ccedil;&atilde;o entre as partes ser&atilde;o regidos pelas leis mencionadas na cl&aacute;usula "14".</p>
<p><strong>17.4</strong> As Partes elegem o Foro da Comarca de S&atilde;o Paulo como sendo o &uacute;nico competente para dirimir quaisquer lit&iacute;gios e/ou demandas que venham a envolver as partes em rela&ccedil;&atilde;o aos servi&ccedil;os prestados.</p>
<p><strong>17.5</strong> A toler&acirc;ncia de uma parte com a outra quanto ao descumprimento de qualquer uma das obriga&ccedil;&otilde;es assumidas neste instrumento n&atilde;o implicar&aacute; em nova&ccedil;&atilde;o ou ren&uacute;ncia de direito. A parte tolerante poder&aacute;, a qualquer tempo, exigir da outra o fiel cumprimento deste.</p>
<p><strong>17.6</strong> O presente instrumento vincula &agrave;s partes e seus sucessores a qualquer t&iacute;tulo.</p>
<p><strong>17.7</strong> A inviabilidade da execu&ccedil;&atilde;o ou invalidade, ainda que em virtude de decis&atilde;o judicial, de alguma cl&aacute;usula, n&atilde;o afetar&aacute; a validade das demais cl&aacute;usulas deste instrumento, que permanecer&aacute; v&aacute;lido e execut&aacute;vel conforme seus termos.</p>
<p><strong>17.8</strong> A BRE COINS se reserva o direito de modificar o presente a qualquer tempo, sendo o usu&aacute;rio comunicado de tais altera&ccedil;&otilde;es, mediante o aceite das novas disposi&ccedil;&otilde;es, nos termos acima.</p>
 	  </div>
    </div>
  </div>
</section>

<?php include('inc/footer.php'); ?>
</body>
</html>
